name = "basic-modmet"
version = "1.0.0"
author = "Marte Voorneveld"
maintainer = "marte.voorneveld@rivm.nl"
copyright = "Copyright 2026, RIVM"

[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false

[install]
library = true

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

[dependencies]
ModMet.git = "https://github.com/rivm-syso/ModMet.git"
ModMet.branch = "develop"

# Use a specific tag or commit for reproducibility, e.g.:3
# ModMet.branch = "main" ! For testing it is better to use a specific tag or commit, e.g.: feature/paths_as_procedures
# run fpm clean --all before switching branches to ensure that the correct version is used

# ModMet.branch = "feature/paths_as_procedures"

# ModMet.tag = "5.0.0"
