name: CI ModMet

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v4
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ hashFiles('modmet.yml') }}
      - uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: modmet.yml
          activate-environment: modmet
          auto-activate-base: false
          use-only-tar-bz2: false
      - name: Install fortitude-lint==0.9.0
        run: pip install fortitude-lint
      - name: Run Fortitude style checker
        run: fortitude check

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v4
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ hashFiles('modmet.yml') }}
      - uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: modmet.yml
          activate-environment: modmet
          auto-activate-base: false
          use-only-tar-bz2: false
      - name: Build with fpm
        shell: bash -el {0}
        run: |
          fpm --version
          fpm build

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v4
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ hashFiles('modmet.yml') }}
      - uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: modmet.yml
          activate-environment: modmet
          auto-activate-base: false
          use-only-tar-bz2: false
      - name: Run tests
        shell: bash -el {0}
        run: fpm test
