name: Deploy Documentation to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy-docs:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}  # Fixed the colon to a dot here
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Conda packages
        uses: actions/cache@v4
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ hashFiles('modmet.yml') }}

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: modmet.yml
          activate-environment: modmet
          auto-activate-base: false
          use-only-tar-bz2: false

      - name: Install FORD
        shell: bash -el {0}
        run: pip install ford

      - name: Build Documentation with FORD
        shell: bash -el {0}
        run: ford ModMet.ford

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'doc/'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4